auth:
  server:
    registration-uri: http://192.168.1.45:9000/api/clients
    authorization-uri: http://192.168.1.45:9000/oauth2/authorize
    token-uri: http://192.168.1.45:9000/oauth2/token
    grant-type: authorization_code
    redirect-uri: http://192.168.1.112:3000/callback
    scope: openid read write
    jwk-set-uri: http://192.168.1.45:9000/oauth2/jwks

spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://192.168.1.45:9000/oauth2/jwks
  application:
    name: resource-server

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: jiwon0126
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: vnbuinfgjkwanuyfivvdshjfgwyuecnyuehwf
  expiration: 604800000

frontend:
  url: http://192.168.1.112:3000